name: 'Testing the SWpath'
description: 'Syncronizing the repository'
inputs:
  key:
    description: 'Secrets'
    required: true
  repo_name:
    description: 'Repository name'
    required: true
outputs:
  message:
    description: "This is the output"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.key }}
    - ${{ inputs.repo_name }}
