- Name: FNV4_Comp1st
  Repository: github.com/Shankarsharm/FNV4_Comp1st.git
  Branch: Jenkins
  lastbuild: b193d3e4c9e451dfa3003b6eeaaf156e764432a0
  Sync_dir: src,test,bin
- Name: FNV4_Comp_2nd
  Repository: github.com/Shankarsharm/FNV4_Comp_2nd.git
  Branch: Jenkins
  lastbuild: b193d3e4c9e451dfa3003b6eeaaf156e764432a0
  Sync_dir: all
- Name: FNV4_Comp_3rd
  Repository: github.com/Shankarsharm/FNV4_Comp_3rd.git
  Branch: Jenkins
  lastbuild: b193d3e4c9e451dfa3003b6eeaaf156e764432a0
  Sync_dir: doc,model
